if(!file.exists("Human Activity Analysis")){dir.create("Human Activity Analysis")}
setwd("Human Activity Analysis")
fileurl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileurl,destfile="./getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip")
unzip("getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip")
directory<-getwd()
Test_Dir<-paste(directory,"UCI HAR Dataset/test",sep="/")
setwd(Test_Dir)
subject_test<-read.table("subject_test.txt")
X_test<-read.table("X_test.txt")
y_test<-read.table("y_test.txt")
Train_Dir<-paste(directory,"UCI HAR Dataset/Train",sep="/")
setwd(Train_Dir)
subject_train<-read.table("subject_train.txt")
X_train<-read.table("X_train.txt")
y_train<-read.table("y_train.txt")
Train_Label<-paste(directory,"UCI HAR Dataset",sep="/")
setwd(Train_Label)
activity_labels<-read.table("activity_labels.txt")
features<-read.table("features.txt")
merge_set<-rbind(X_test,X_train)
merge_label<-rbind(y_test,y_train)
merge_subject<-rbind(subject_test,subject_train)
names(merge_set)<-features$V2
names(merge_subject)<-c("Subject")
names(merge_label)<-c("Label")
final_merge_dataset<-cbind(merge_subject,merge_label,merge_set)
write.csv(final_merge_dataset,"final_merge_dataset.csv", eol = "\n")
final_merge_dataset_small<-final_merge_dataset[,names(final_merge_dataset) %in% grep("Subject|Label|[Ss][Tt][Dd]|[Mm][Ee][Aa][Nn]",colnames(final_merge_dataset),value=T)]
names(final_merge_dataset_small)<-gsub("//(//)","",names(final_merge_dataset_small))
names(final_merge_dataset)<-gsub("//(//)","",names(final_merge_dataset))
names(features)<-c("Label","Label_name")
names(final_merge_dataset_small)<-gsub("^t", "time", names(final_merge_dataset_small))
names(final_merge_dataset_small)<-gsub("^f", "frequency", names(final_merge_dataset_small))
names(final_merge_dataset_small)<-gsub("Acc", "Accelerometer", names(final_merge_dataset_small))
names(final_merge_dataset_small)<-gsub("Gyro", "Gyroscope", names(final_merge_dataset_small))
names(final_merge_dataset_small)<-gsub("Mag", "Magnitude", names(final_merge_dataset_small))
names(final_merge_dataset_small)<-gsub("BodyBody", "Body", names(final_merge_dataset_small))
final_merge_label_dataset_small<-merge(final_merge_dataset_small,features,by = "Label")
final_merge_label_dataset_small<-final_merge_label_dataset_small[ ,!(names(final_merge_label_dataset_small) %in% "Label")]
agg<-aggregate(. ~Label_name + Subject, final_merge_label_dataset_small, mean)
write.csv(agg,"agg.csv", eol = "\n")